//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiUsuario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbMiUsuarioEntities : DbContext
    {
        public dbMiUsuarioEntities()
            : base("name=dbMiUsuarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TMiUsuario> TMiUsuario { get; set; }
        public virtual DbSet<TUsuarioPrincipal> TUsuarioPrincipal { get; set; }
    
        public virtual int TMiUsuarioEliminar(Nullable<int> miId)
        {
            var miIdParameter = miId.HasValue ?
                new ObjectParameter("MiId", miId) :
                new ObjectParameter("MiId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TMiUsuarioEliminar", miIdParameter);
        }
    
        public virtual int TMiUsuarioInsertar(string miRef, string miUsu, string miCon, string miDir, string miIma)
        {
            var miRefParameter = miRef != null ?
                new ObjectParameter("MiRef", miRef) :
                new ObjectParameter("MiRef", typeof(string));
    
            var miUsuParameter = miUsu != null ?
                new ObjectParameter("MiUsu", miUsu) :
                new ObjectParameter("MiUsu", typeof(string));
    
            var miConParameter = miCon != null ?
                new ObjectParameter("MiCon", miCon) :
                new ObjectParameter("MiCon", typeof(string));
    
            var miDirParameter = miDir != null ?
                new ObjectParameter("MiDir", miDir) :
                new ObjectParameter("MiDir", typeof(string));
    
            var miImaParameter = miIma != null ?
                new ObjectParameter("MiIma", miIma) :
                new ObjectParameter("MiIma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TMiUsuarioInsertar", miRefParameter, miUsuParameter, miConParameter, miDirParameter, miImaParameter);
        }
    
        public virtual ObjectResult<TMiUsuarioListar_Result> TMiUsuarioListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TMiUsuarioListar_Result>("TMiUsuarioListar");
        }
    
        public virtual int TMiUsuarioModificar(Nullable<int> miId, string miRef, string miUsu, string miCon, string miDir, string miIma)
        {
            var miIdParameter = miId.HasValue ?
                new ObjectParameter("MiId", miId) :
                new ObjectParameter("MiId", typeof(int));
    
            var miRefParameter = miRef != null ?
                new ObjectParameter("MiRef", miRef) :
                new ObjectParameter("MiRef", typeof(string));
    
            var miUsuParameter = miUsu != null ?
                new ObjectParameter("MiUsu", miUsu) :
                new ObjectParameter("MiUsu", typeof(string));
    
            var miConParameter = miCon != null ?
                new ObjectParameter("MiCon", miCon) :
                new ObjectParameter("MiCon", typeof(string));
    
            var miDirParameter = miDir != null ?
                new ObjectParameter("MiDir", miDir) :
                new ObjectParameter("MiDir", typeof(string));
    
            var miImaParameter = miIma != null ?
                new ObjectParameter("MiIma", miIma) :
                new ObjectParameter("MiIma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TMiUsuarioModificar", miIdParameter, miRefParameter, miUsuParameter, miConParameter, miDirParameter, miImaParameter);
        }
    }
}
