//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiUsuario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMiUsuario
    {
        public int Id { get; set; }
        public string Referencia { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string DireccionPagina { get; set; }
        public string Imagen { get; set; }
    }
}
